export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"首页","i":"home"},["/README.md"]],
  ["v-b174039c","/document/imgProcess.html",{"y":"a","t":"图片预处理","i":"image"},[":md"]],
  ["v-36b1a79b","/document/",{"y":"a","t":"开发文档","i":"code"},["/document/README.md"]],
  ["v-740adfb8","/file/constitution.html",{"y":"a","t":"社团章程"},[":md"]],
  ["v-0b155d30","/file/fainance.html",{"y":"a","t":"财务报表"},[":md"]],
  ["v-1491bada","/file/",{"y":"a","t":"资料公开","i":"file"},["/file/README.md"]],
  ["v-1876ad68","/file/zhidao.html",{"y":"a","t":"学生社团活动指导"},[":md"]],
  ["v-2d0a983f","/ja/",{"y":"h","t":"ホームページ","i":"home"},["/ja/README.md"]],
  ["v-2e1e9184","/notice/",{"y":"h","t":"通知","i":"bullhorn"},["/notice/README.md"]],
  ["v-07ad1a70","/journal/7-8.html",{"y":"a","t":"7-8周"},[":md"]],
  ["v-d04bbc5e","/journal/",{"y":"a","t":"周报","i":"eye"},["/journal/README.md"]],
  ["v-8c1f462c","/ja/file/constitution.html",{"y":"h","t":"社团章程"},[":md"]],
  ["v-3b247154","/ja/file/",{"y":"h","t":"資料","i":"file"},["/ja/file/README.md"]],
  ["v-94a09190","/ja/notice/",{"y":"h","t":"お知らせ","i":"bullhorn"},["/ja/notice/README.md"]],
  ["v-538c91eb","/ja/notice/guide/",{"y":"a","t":"Guide","i":"lightbulb"},["/ja/notice/guide/README.md"]],
  ["v-ea701cf6","/ja/notice/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-940caa32","/ja/notice/guide/bar/",{"y":"a","t":"Bar feature","i":"lightbulb"},["/ja/notice/guide/bar/README.md"]],
  ["v-6d91ef83","/ja/notice/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-94089ed8","/ja/notice/guide/foo/",{"y":"a","t":"Foo feature","i":"lightbulb"},["/ja/notice/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
